"""
audit_registrations.py -- docs/REGISTRATION_AUDIT.md: for each rule written before an analysis, the time it was fixed and
the earliest time any file it governs existed, with the evidence for each time.

Evidence, strongest first:
- git: the commit that first added the rule (cannot be reset by editing the file);
- the content hash, where the rule records one (the anatomic constraints);
- the file's birth time (stat). An in-place edit (`sed -i`) resets it; where that happened it is recorded below, and the
  file time is not used as evidence.

Governed files are results/ artefacts, so their times are birth times on this machine: on a fresh clone they cannot be
re-checked, which is why the audit is written to a tracked document with the times it read.

    python3 scripts/audit_registrations.py
"""
from __future__ import annotations

import subprocess
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from ivygap import config  # noqa: E402

DOC = ROOT / "docs" / "REGISTRATION_AUDIT.md"
R = config.RESULTS_DIR

# rule -> the files whose existence the rule must precede, and any known caveat about the rule's own timestamp
RULES = [
    ("ivygap/anatomic/constraints.py", ["results_archive/2026-09-05T2154/MANIFEST.json"],
     "Content hash 2d1fb47c... equals the first scoring run's recorded hash and the OSF deposit (dm2t8, 2026-09-10); "
     "the file is unchanged since its first commit."),
    ("prespecified/immune_failure_factors.md", ["results/methylation_celltypes_lgg.csv", "results/methylation_celltypes_lgg.json"],
     "The T > B prediction and its falsifier."),
    ("prespecified/identifiability_diagnostics.md", ["results/identifiability/unmix_gbm_s1.csv", "results/identifiability/unmix_lgg_s1.csv"],
     "E2."),
    ("prespecified/gimicc_truth_confirmation.md", ["results/gimicc/runs/gbm_GBM_h4.csv", "results/gimicc/runs/lgg_AST_h4.csv"],
     "KNOWN: an in-place `sed -i` on 2026-10-03 reset this file's birth time to 13:03:58. Its original creation, "
     "12:51:36, is recorded in the session record and docs/STS_WORKLOG.md, not on the filesystem, so the file time "
     "below cannot prove precedence for this rule."),
    ("prespecified/atlas_t_vs_b.md", ["results/atlas_t_vs_b.json"], "Direct counts, two atlases."),
    ("prespecified/klemm_t_vs_b.md", ["results/klemm_t_vs_b.json"], "Flow cytometry (Klemm 2020, Figure 1F)."),
    ("prespecified/cptac_per_sample_truth.md", ["results/cptac/snrna_truth.csv", "results/cptac/estimates_frozen.csv"],
     "Written while the CPTAC download was running (raw files from 20:43; manifest complete 20:52:52); the governed "
     "files are the first derived from them."),
    ("prespecified/cptac_wgs_purity_secondary.md", ["data/external/cptac_gbm/wgs_ascat_purity.tsv",
                                                    "data/external/cptac_gbm/pathology_tumor_nuclei.tsv"],
     "Secondary; written after the primary was read and before any purity or pathology value was fetched."),
    ("prespecified/identifiability_e3_gene_resampling.md", ["results/identifiability/e3/unmix_gbm_sub00.csv"], "E3."),
]


def birth(p: Path) -> datetime | None:
    if not p.exists():
        return None
    st = p.stat()
    return datetime.fromtimestamp(getattr(st, "st_birthtime", st.st_mtime))


def first_commit(path: str) -> tuple[datetime | None, str]:
    out = subprocess.run(["git", "log", "--diff-filter=A", "--follow", "--format=%at %h", "--", path],
                         cwd=ROOT, capture_output=True, text=True).stdout.split()
    if len(out) < 2:
        return None, "not committed"
    return datetime.fromtimestamp(int(out[-2])), out[-1]


def main() -> int:
    L = ["# Registration audit: was each rule fixed before the data it governs?", "",
         "*Generated by `scripts/audit_registrations.py`. Times are local (EDT). 'Fixed' uses the git commit where "
         "it is earlier than the file's birth or the birth time is known to have been reset; otherwise the file's "
         "birth time (stat). 'First governed file' is the earliest birth time among the files the rule governs.*", "",
         "| rule | fixed (evidence) | first governed file | margin | verdict |", "|---|---|---|---|---|"]
    notes = []
    for rule, governed, note in RULES:
        rp = ROOT / rule
        fb = birth(rp)
        gc, gh = first_commit(rule)
        reset = "KNOWN:" in note
        if reset:
            fixed, ev = (gc, f"git {gh}") if gc else (None, "unprovable from the filesystem")
        else:
            cands = [(t, e) for t, e in ((fb, "file birth"), (gc, f"git {gh}")) if t is not None]
            fixed, ev = min(cands) if cands else (None, "missing")
        gtimes = [(birth(ROOT / g), g) for g in governed if (ROOT / g).exists()]
        gfirst = min(gtimes) if gtimes else (None, None)
        if fixed is None or gfirst[0] is None:
            verdict, margin = "CANNOT CHECK", "--"
        else:
            dt = (gfirst[0] - fixed).total_seconds()
            margin = f"{dt / 60:+.1f} min" if abs(dt) < 86400 else f"{dt / 86400:+.1f} days"
            verdict = "PRECEDES" if dt > 0 else ("NOT PROVABLE HERE (see note)" if reset else "AFTER")
        L.append(f"| `{rule}` | {fixed:%Y-%m-%d %H:%M:%S} ({ev}) | " if fixed else f"| `{rule}` | -- ({ev}) | ")
        L[-1] += (f"{gfirst[0]:%Y-%m-%d %H:%M:%S} `{gfirst[1]}` | {margin} | **{verdict}** |" if gfirst[0]
                  else "-- | -- | **CANNOT CHECK** |")
        notes.append(f"- `{rule}`: {note}")
    L += ["", "## Notes", ""] + notes
    DOC.write_text("\n".join(L) + "\n")
    print("\n".join(L[5:5 + len(RULES)]))
    print(f"wrote {DOC.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
